version: 0.2
env:
  variables:
    GIT_URL: "babysori@github.com:babysori/defaultApiServer.git"
  parameter-store:
    SSH_KEY: git_key
    SSH_PUB: git_pub
    JWT_KEY: jwt_key
    JWT_PUB: jwt_pub

phases:
  install:
    commands:
      - mkdir -p ~/.ssh
      - echo "$SSH_KEY" > ~/.ssh/id_rsa
      - echo "$SSH_PUB" > ~/.ssh/id_rsa.pub
      - mkdir .keys
      - echo "$JWT_KEY" > .keys/jwtrs256.key
      - echo "$JWT_PUB" > .keys/jwtrs256.key.pub
      - chmod 600 ~/.ssh/id_rsa .keys/jwtrs256.key
      - eval "$(ssh-agent -s)"
      - git init
      - git remote add origin "$GIT_URL"
      - git fetch origin
      - git branch
      - git checkout -f "$CODEBUILD_RESOLVED_SOURCE_VERSION"
      - git submodule init
      - git submodule update --recursive

artifacts:
  files:
    - "**/*"
cache:
  paths:
    - "node_modules/**/*"
