version: 0.2
env:
  variables:
    GIT_URL: "git@github.com:babysori/defaultApiServer.git"
  parameter-store:
    SSH_KEY: git_key
    JWT_KEY: jwt_key
    JWT_PUB: jwt_pub

phases:
  install:
    commands:
      - mkdir -p ~/.ssh .keys
      - echo "$JWT_KEY" > .keys/jwtrs256.key
      - echo "$JWT_PUB" > .keys/jwtrs256.key.pub
      - echo "$SSH_KEY" > ~/.ssh/id_rsa
      - wget https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem
      - mv rds-combined-ca-bundle.pem .keys/
      - chmod 600 ~/.ssh/id_rsa
      - eval "$(ssh-agent -s)"
      - ssh-add ~/.ssh/id_rsa
      - git config --global url."git@github.com:".insteadOf "https://github.com/"
      - git init
      - git remote add origin "$GIT_URL"
      - git fetch origin
      - git branch
      - git checkout -f "$CODEBUILD_RESOLVED_SOURCE_VERSION"
      - git submodule init
      - git submodule update --recursive

artifacts:
  files:
    - "**/*"
cache:
  paths:
    - "node_modules/**/*"
