swagger: "2.0"
info:
  description: "Default APIs"
  version: "0.9.0"
  title: "Default API SWAGGER"
  contract: "babysori@gamil.com"
basePath: "/v1"
tags:
  - name: "account"
    description: "계정관리"
  - name: "token"
    description: "토큰관리"
paths:
  /account:
    post:
      tags:
        - "account"
      summary: "계정 생성"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "생성할 계정정보를 입력한다."
          required: true
          schema:
            type: "object"
            properties:
              type:
                type: "string"
                description: "계정 타입. default: email"
                enum:
                  - "email"
                  - "google"
                  - "apple"
                  - "fb"
                  - "kakao"
                  - "naver"
                  - "line"
              id:
                type: "string"
                description: "생성할 계정의 ID"
                required: true
              password:
                type: "string"
                description: "비밀번호. email 타입일 경우에만 입력."
              socialIdToken:
                type: "string"
                description: "google 타입 계정만 필요함."
              socialAccessToken:
                type: "string"
                description: "Social 계정만 필요함."
      responses:
        "200":
          descrption: "성공"
    put:
      tags:
        - "account"
      summary: "계정 로그인"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "로그인할 계정의 정보를 입력한다."
          required: true
          schema:
            type: "object"
            properties:
              type:
                type: "string"
                description: "계정 타입. default: email"
                enum:
                  - "email"
                  - "google"
                  - "apple"
                  - "fb"
                  - "kakao"
                  - "naver"
                  - "line"
              id:
                type: "string"
                description: "로그인할 계정의 ID"
                required: true
              password:
                type: "string"
                description: "비밀번호. email 타입일 경우에만 입력."
              socialIdToken:
                type: "string"
                description: "google 타입 계정만 필요함."
              socialAccessToken:
                type: "string"
                description: "Social 계정만 필요함."
      responses:
        "200":
          descrption: "성공"

  /token:
    get:
      tags:
        - "token"
      summary: "토큰 갱신(refresh)"
      produces:
        - "application/json"
      responses:
        "200":
          descrption: "성공"
          schema:
            type: "object"
            properties:
              access_key:
                type: "string"
                description: "갱된 access key"
